### ISSUE TITLE
How bout them docs  :)

### ISSUE THREAD

**Issue by Eco-logical** [airdcpp/airdcpp-webapi#1]
Hey I really like what you guys are doing with the client but the lack of docs makes me sad :(

1) is there a dev hub that we can rally at?  If not we can make that happen.
2) are there docs on the json end points/payloads
3) if you have tested what works with verlihub and flexhub
4) the -> [See the Websocket API documentation for details](https://github.com/airdcpp/airdcpp-webapi#websockets) <- points back on itself

I would like to look at developing a python API but not willing to dig thru everything to make that happen.

Thx,
Ecological

**Comment by maksis** [comment]
Sorry for the late response.

Yeah, docs should definitely be written. At the moment the API is generally written based on what's needed by the Web UI. If you have suggestions about good documentation frameworks to use, I'd like to hear about those.

> is there a dev hub that we can rally at? If not we can make that happen.

Having a dev hub would be a good idea indeed.

> if you have tested what works with verlihub and flexhub

Do you mean the protocol (NMDC) limitations? There aren't many limitations that would affect the API usage directly. However, the internal functionality is often different (and more unreliable) in NMDC hubs. It's also not possible to send search queries to individual users in NMDC hubs.

**Comment by Eco-logical** [comment]
> If you have suggestions about good documentation frameworks to use, I'd like to hear about those.

I would say something you can integrate into GitHub if it were me.  So you can make changes in git and ppl can contribute. 

Some popular ones that I have seen are:

[Read the Docs](https://readthedocs.org/)
[RTD docs](https://docs.readthedocs.io/en/latest/index.html)

[Sphinx](https://github.com/sphinx-doc/sphinx/)
[sphinx-autobuild](https://github.com/GaretJax/sphinx-autobuild)
[You can host the pages with](https://guides.github.com/features/pages/)

[Or just use GitHub's wiki (I would make it so you can pull/push/edit remote) ](https://help.github.com/articles/about-github-wikis/)



> Do you mean the protocol (NMDC) limitations?

Yeah I saw the something regarding limitations in NMDC and i think some limitations to Flex in particular.  That may have been in your specific JS API however.

>However, the internal functionality is often different (and more unreliable) in NMDC hubs. It's also not possible to send search queries to individual users in NMDC hubs.

As far as the functionality.  If i understand you can still search NMDC hubs for files however not individual users lists?  A use case I was thinking about was a bot to search a users file list for prohibited files on reg or entry or something.  I could work around this however.

**Comment by Eco-logical** [comment]
whoops wrong button

**Comment by maksis** [comment]
Docs are now available at http://docs.airdcpp.apiary.io

API v1 won't go final anytime soon so there is time for testing and feature requests.
